$(arg left_fisheye_node_name):
  update_rate: &fisheye_update_rate 10
  always_recompute_mapping: false
  base_frame: $(arg camera_name)_center_link
  pose: [0, 0, 0, 0, 0, 1.57]
  virtual_sensor_frame: camera360_ideal_fisheye_left_link
  virtual_sensor_optical_frame: camera360_ideal_fisheye_left_optical_frame
  projection_type: image_projection_plugins::IdealFisheyeProjection
  projection_parameters:
    image_width: &fisheye_resolution 512
    image_height: *fisheye_resolution
    fov: &fisheye_fov 180
    sphere_radius: &fisheye_sphere_radius 1
$(arg right_fisheye_node_name):
  update_rate: *fisheye_update_rate
  always_recompute_mapping: false
  base_frame: $(arg camera_name)_center_link
  pose: [0, 0, 0, 0, 0, -1.57]
  virtual_sensor_frame: camera360_ideal_fisheye_right_link
  virtual_sensor_optical_frame: camera360_ideal_fisheye_right_optical_frame
  projection_type: image_projection_plugins::IdealFisheyeProjection
  projection_parameters:
    image_width: *fisheye_resolution
    image_height: *fisheye_resolution
    fov: *fisheye_fov
    sphere_radius: *fisheye_sphere_radius
