length_in_x: 4.0
length_in_y: 4.0
position_x: 0.0
position_y: 0.0
resolution: 0.05
min_variance: 0.001
max_variance: 100.0
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.02
surface_normal_estimation_radius: 0.24
surface_normal_positive_axis: z
global_map: true
