# Traversability map filter parameters
traversability_map_filters:
  - name: surfaceNormalsFilter
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation
      output_layers_prefix: surface_normal_
      radius: 0.15
      normal_vector_positive_axis: z
  - name: slopeFilter
    type: traversabilityFilters/SlopeFilter
    params:
      map_type: traversability_slope
      critical_value: 0.85
  - name: stepFilter
    type: traversabilityFilters/StepFilter
    params:
      map_type: traversability_step
      critical_value: 0.12
      first_window_radius: 0.1
      second_window_radius: 0.1
      critical_cell_number: 4
  - name: negativeStepFilter
    type: traversabilityFilters/NegativeStepFilter
    params:
      map_type: traversability_negative_step
      max_allowed_step_depth: 0.15
      sample_distance_cells: 10
      critical_cell_number: 3      
  #- name: roughnessFilter
  #  type: traversabilityFilters/RoughnessFilter
  #  params:
  #    map_type: traversability_roughness
  #    critical_value: 0.05
  #    estimation_radius: 0.15
  - name: FuseFilter
    type: traversabilityFilters/FuseFilter
    params:
      map_type: traversability
      max_allowed_step_depth: 0.15
      sample_distance_cells: 10
      critical_cell_number: 3         
  #- name: weightedSumFilter
  #  type: gridMapFilters/MathExpressionFilter
  #  params:
  #    output_layer: traversability
  #    expression:  (1.0/2.0) * (((1.0 / 3.0) * (traversability_slope + traversability_step + traversability_roughness)) + traversability_negative_step * 0.25)
  - name: deletionFilter
    type: gridMapFilters/DeletionFilter
    params:
      layers: [surface_normal_x, surface_normal_y, surface_normal_z]
