# Footprint parameters
footprint:
  footprint_polygon: [[0.60, 0.21], [0.60, -0.21], [-0.40, -0.21], [-0.40, 0.21]] # Vertices of footprint polygon with coordinates [x, y] in robot footprint frame.
  circular_footprint_radius: 0.4
  circular_footprint_radius_inscribed: 0.4
  circular_footprint_offset: 0.0
  footprint_frame_id: base_link
  traversability_default: 0.3
